### PR TITLE
Use a different cache directory for tests

### LINKED ISSUE #400: Better test suite
There are two things that annoy me with the test suite

- [ ] We clear **ALL** castor castor cache (so all other real projet suffers) 

- [x] We cannot run the test suite twice because:
    ```
    >…egoire/dev/github.com/jolicode/castor(main) ./vendor/bin/simple-phpunit tests/Generated/ImportSamePackageWithDefaultVersionTest.php
    PHPUnit 9.6.19 by Sebastian Bergmann and contributors.

    Runtime:       PHP 8.3.4
    Configuration: /home/gregoire/dev/github.com/jolicode/castor/phpunit.xml

    Testing Castor\Tests\Generated\ImportSamePackageWithDefaultVersionTest
    .                                                                   1 / 1 (100%)

    Time: 00:00.610, Memory: 4.00 MB

    OK (1 test, 4 assertions)
    >…egoire/dev/github.com/jolicode/castor(main) ./vendor/bin/simple-phpunit tests/Generated/ImportSamePackageWithDefaultVersionTest.php
    PHPUnit 9.6.19 by Sebastian Bergmann and contributors.

    Runtime:       PHP 8.3.4
    Configuration: /home/gregoire/dev/github.com/jolicode/castor/phpunit.xml

    Testing Castor\Tests\Generated\ImportSamePackageWithDefaultVersionTest
    F                                                                   1 / 1 (100%)

    Time: 00:00.304, Memory: 4.00 MB

    There was 1 failure:

    1) Castor\Tests\Generated\ImportSamePackageWithDefaultVersionTest::test
    Failed asserting that two strings are equal.
    --- Expected
    +++ Actual
    @@ @@
    -' Downloading remote packages\n
    - Remote packages imported\n
    -\n
    -castor v.X.Y.Z\n
    +'castor v.X.Y.Z\n
    \n
    Usage:\n
      command [options] [arguments]\n

    /home/gregoire/dev/github.com/jolicode/castor/tests/TaskTestCase.php:63
    /home/gregoire/dev/github.com/jolicode/castor/tests/Generated/ImportSamePackageWithDefaultVersionTest.php:15

    FAILURES!
    Tests: 1, Assertions: 3, Failures: 1.
    >…egoire/dev/github.com/jolicode/castor(main) rm tests/fixtures/valid/import-same-package-with-default-version/.castor/vendor/ -rf
    >…egoire/dev/github.com/jolicode/castor(main) ./vendor/bin/simple-phpunit tests/Generated/ImportSamePackageWithDefaultVersionTest.php
    PHPUnit 9.6.19 by Sebastian Bergmann and contributors.

    Runtime:       PHP 8.3.4
    Configuration: /home/gregoire/dev/github.com/jolicode/castor/phpunit.xml

    Testing Castor\Tests\Generated\ImportSamePackageWithDefaultVersionTest
    .                                                                   1 / 1 (100%)

    Time: 00:00.701, Memory: 4.00 MB

    OK (1 test, 4 assertions)
    ```
fixed in #407

### PR DESCRIPTION
**Pull request by pyrech**
Fix #400

### CODE REVIEW

**Review by lyrixx — APPROVED** [review]
So simple! I like it! thanks

**Comment by TheoD02** [comment]
Hello,

Some change missing in `FingerprintedTestCase` to fix the failing test 😉

https://github.com/jolicode/castor/blob/685a805b98ec031777df1bb1753d1da060a3e8e1/tests/Examples/Fingerprint/FingerprintedTestCase.php#L23-L41

**Comment by pyrech** [comment]
Tests fixed, and I additionally renamed the method `PlatformHelper::getCacheDirectory()`  to `PlatformHelper::getDefaultCacheDirectory()` better reflect the fact that it can change at runtime.

**Review by lyrixx — APPROVED** [review]

**Comment by lyrixx** [comment]
Awesome, thanks

**Pull request merged**
