### PR TITLE
WIP: debug arm64 macos

### PR DESCRIPTION
**Pull request by joelwurtz**

### CODE REVIEW

**Comment by joelwurtz** [comment]
Here is the error for building on mac arm64

image

> configure: error: pcntl: fork() not supported by this platform

@tucksaun I know that you worked on the initial PR for this support do you have any pointers for that ?

**Comment by joelwurtz** [comment]
The only that changes between the working version and none working was the runne image

Working : 20240402.2 version
Not Working : 20240405.1 version

**Comment by tucksaun** [comment]
@joelwurtz nothing I can think of right now but I can have a look next week if you want

**Comment by tucksaun** [comment]
@joelwurtz ~The good news is that I managed to reproduce the error locally, the bad news is that if run the configure command line directly (which is the one failing) then it works...~
~Actually, invoking spc directly builds successfully also.~

I think I found it ! sending a PR right now 🤞

**Comment by tucksaun** [comment]
(see #413)

**Comment by lyrixx** [comment]
I think we could close this one thanks to https://github.com/jolicode/castor/pull/413?

**Comment by joelwurtz** [comment]
Will close this, i also use stable version of spc in this PR do you want that i create a new PR to do this ? I think it would be better in term of stability

**Pull request closed without merging**
