### PR TITLE
fix(#512): repack command work without .castor folder

### PR DESCRIPTION
**Pull request by arnolem**
https://github.com/jolicode/castor/issues/512

### CODE REVIEW

**Comment by lyrixx** [comment]
Hello @arnolem ; Thanks for the PR. 

Could you look at failing test? Thanks

**Comment by lyrixx** [comment]
hmm, nevermind, it looks like we have some failures on main branch

**Review by lyrixx — APPROVED** [review]
I have rebased your PR. 

Thanks for the fix 👏🏼

**Review by pyrech — APPROVED** [review]
Thanks for the fix. It deserves a note in the changelog IMO

**Comment by lyrixx** [comment]
> Thanks for the fix. It deserves a note in the changelog IMO

It did it 👍🏼 

Thanks again @arnolem

**Comment by arnolem** [comment]
> Thanks for the fix. It deserves a note in the changelog IMO

Okay, I'll know for next time.

**Pull request merged**
