### PR TITLE
feat(run): deprecate parameters in run function that are in context

### PR DESCRIPTION
**Pull request by joelwurtz**
Goal is each parameters that is available in context should not be duplicated in the run function (or function depending on it), should simplify calls in the futures

### CODE REVIEW

**Review by pyrech — COMMENTED** [review]
I wonder whether the documentation should stay in the run section? If not, paragraph will need to be reworded to precise that it concerns the process execution through the `run()` helper.

LGTM otherwise

**Review by lyrixx — COMMENTED** [review]
LGTM too 👍🏼 same question as @pyrech

**Comment by joelwurtz** [comment]
I was wondering the same about context, but since context may be used in other place that the run method, i think it's better to have documentation about it in the context section and not the run section, even if somes parameters are linked to the run function, they may be used when another method will use the `run` method (more it's helper but it's the same)

So for me documentation about those parameters should be in context section not in the run one, maybe we could add some links inside the run documentation to help this

**Comment by lyrixx** [comment]
Could you rebase + add a note in the CHANGELOG?

**Comment by joelwurtz** [comment]
done

**Review by lyrixx — APPROVED** [review]

**Pull request merged**
