### PR TITLE
Do not build static-darwin-arm64 binary anymore (may be temporary)

### PR DESCRIPTION
**Pull request by lyrixx**
Too many errors

### CODE REVIEW

**Review by pyrech — APPROVED** [review]
Thanks :face_holding_back_tears:

**Comment by gubler** [comment]
Are those of us on Mac ARM now supposed to use global composer?

I can understand if the build is causing problems, but I would like to know what the recommended update/install process is now.

**Comment by lyrixx** [comment]
It would be awesome if someone could debug the build system. I don't own a mac ARM so I cannot help :/

**Comment by pyrech** [comment]
The recommended way is still to use the Phar version, not the global composer install

**Comment by pyrech** [comment]
The darwin arm build that was removed is only for the static binary (the one standalone embedding PHP). But the phar version is still build and released, so you can use the installer (or download the phar directly). Hope it answers your question :)

**Comment by tucksaun** [comment]
@lyrixx do you want some help?

**Comment by tucksaun** [comment]
I might have some time next week, I keep you posted 😉

**Comment by ptondereau** [comment]
I tried to build locally on my M2 and it worked well:
CleanShot 2024-10-12 at 09 50 30@2x

I'll try investigating on the GA container then

**Pull request merged**
